FROM python:3.10.0-buster AS builder

RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends pipenv \
    && pip install --upgrade pipenv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Pipfile Pipfile.lock ./

RUN pipenv install --deploy

FROM python:3.10.0-buster

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY . .

EXPOSE 7890

ENTRYPOINT ["python3"]
CMD ["a.py"]