services:
  micmic-backend:
     build:
       dockerfile: Dockerfile
     ports:
      - "7890:7890"
     env_file:
       - .env
     environment:
       STAGE: '${STAGE}'
       MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
       MYSQL_HOST: '${MYSQL_HOST}'
       MYSQL_DB: '${MYSQL_DB}'
       MYSQL_PORT: '${MYSQL_PORT}'
       MYSQL_USER: '${MYSQL_USER}'
     restart: always
     networks:
       - micmic_backend
networks:
  micmic_backend:
    external: true