  name: Push Docker Image to Docker Hub
  on:
    push:
      branches:
        - 'master'
      tags:
        - '**'
  jobs:
    push:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Docker meta
          id: docker_meta
          uses: crazy-max/ghaction-docker-meta@v1
